### ISSUE TITLE
ss changes branch docker error

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#120]
I attempted to bring the ss-changes branch up in docker and ran into a "no such file or directory, uv_resident_set_memory" on web_1. Do you have any thoughts on what I'm missing?

```
rtkueh01@localhost hyku-ss-changes % sc pull           
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
         run  dotenv -f .env.development,.env docker-compose pull web  from "."
No such file or directory @ rb_sysopen - /Users/rtkueh01/Documents/notch8/hyku-ss-changes/.env.development
rtkueh01@localhost hyku-ss-changes % sc build
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
      create  .env.development
         run  dotenv -f .env.development,.env docker-compose build web from "."
WARNING: The JAVA_OPTS variable is not set. Defaulting to a blank string.
Building web
[+] Building 2664.9s (17/17) FINISHED                                           
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 2.94kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 473B                                          0.0s
 => [internal] load metadata for ghcr.io/samvera/hyrax/hyrax-base:3.1.0    0.8s
 => [hyku-base  1/12] FROM ghcr.io/samvera/hyrax/hyrax-base:3.1.0@sha256:  0.0s
 => [internal] load build context                                          0.3s
 => => transferring context: 8.49MB                                        0.3s
 => CACHED [hyku-base  2/12] RUN apk --no-cache upgrade &&   apk --no-cac  0.0s
 => CACHED [hyku-base  3/12] RUN wget https://imagemagick.org/download/Im  0.0s
 => CACHED [hyku-base  4/12] RUN set -x -o pipefail     && wget -O- https  0.0s
 => CACHED [hyku-base  5/12] RUN mkdir -p /app/fits &&     cd /app/fits &  0.0s
 => [hyku-base  6/12] COPY --chown=1001:101 /ops/fits.xml /app/fits/xml/f  0.0s
 => [hyku-base  7/12] COPY --chown=1001:101 /ops/exiftool_image_to_fits.x  0.0s
 => [hyku-base  8/12] RUN ln -sf /usr/lib/libmediainfo.so.0 /app/fits/too  0.2s
 => [hyku-base  9/12] COPY --chown=1001:101 /Gemfile* /app/samvera/hyrax-  0.0s
 => [hyku-base 10/12] RUN bundle install --jobs "$(nproc)"              1673.3s
 => [hyku-base 11/12] COPY --chown=1001:101  /app/samvera/hyrax-webapp     0.1s
 => [hyku-base 12/12] RUN sh -l -c "   yarn install &&   RAILS_ENV=prod  986.1s 
 => exporting to image                                                     3.9s 
 => => exporting layers                                                    3.9s
 => => writing image sha256:3a91658607e3f41a094fd13be974570a5c1d55fae81da  0.0s
 => => naming to registry.gitlab.com/notch8/louisville-hyku:latest         0.0s
rtkueh01@localhost hyku-ss-changes % sc up   
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
         run  dotenv -f .env.development,.env docker-compose up --remove-orphans web from "."
WARNING: The JAVA_OPTS variable is not set. Defaulting to a blank string.
Creating network "hyku-ss-changes_internal" with the default driver
Creating volume "hyku-ss-changes_fcrepo" with default driver
Creating volume "hyku-ss-changes_solr" with default driver
Creating volume "hyku-ss-changes_db" with default driver
Creating volume "hyku-ss-changes_redis" with default driver
Creating volume "hyku-ss-changes_zk" with default driver
Creating volume "hyku-ss-changes_uploads" with default driver
Creating volume "hyku-ss-changes_assets" with default driver
Creating volume "hyku-ss-changes_cache" with default driver
Creating volume "hyku-ss-changes_uv" with default driver
Creating hyku-ss-changes_db_1            ... done
Creating hyku-ss-changes_check_volumes_1 ... done
Creating hyku-ss-changes_fcrepo_1        ... done
Creating hyku-ss-changes_chrome_1        ... done
Creating hyku-ss-changes_redis_1         ... done
Creating hyku-ss-changes_zoo_1           ... done
Creating hyku-ss-changes_solr_1          ... done
Creating hyku-ss-changes_initialize_app_1 ... done
Creating hyku-ss-changes_worker_1         ... done
Creating hyku-ss-changes_web_1            ... done
Attaching to hyku-ss-changes_web_1
web_1             | Error: ENOENT: no such file or directory, uv_resident_set_memory
web_1             |     at process.memoryUsage (internal/process/per_thread.js:152:5)
web_1             |     at ConsoleReporter.checkPeakMemory (/usr/share/node_modules/yarn/lib/cli.js:33565:40)
web_1             |     at ConsoleReporter.initPeakMemoryCounter (/usr/share/node_modules/yarn/lib/cli.js:33556:10)
web_1             |     at /usr/share/node_modules/yarn/lib/cli.js:92291:14
web_1             |     at Generator.next (<anonymous>)
web_1             |     at step (/usr/share/node_modules/yarn/lib/cli.js:310:30)
web_1             |     at /usr/share/node_modules/yarn/lib/cli.js:328:14
web_1             |     at new Promise (<anonymous>)
web_1             |     at new F (/usr/share/node_modules/yarn/lib/cli.js:5301:28)
web_1             |     at /usr/share/node_modules/yarn/lib/cli.js:307:12
hyku-ss-changes_web_1 exited with code 1
```

**Comment by orangewolf** [comment]
[@rtkuehn](https://github.com/rtkuehn) Just to help narrow this down, could you try using docker commands instead of stack car? Do you get the same error?

**Comment by orangewolf** [comment]
Randy March 2022
---
The "no such file or directory, uv_resident_set_memory" error seems to be an occasional error. I've seen it when using docker compose...not sure if I've seen it using stack car. Rerunning dc up seems to resolve the issue every time. We can probably close it.

**Comment by orangewolf** [comment]
Randy March 2022
---
@ShanaLMoore Yes, the same error appears. I've mainly been using dc rather than sc because I was under the impression that sc did not load the .env variables. Am I mistaken?
While I'm on the subject, I basing my testing on the following...
1. The .env file needs to be loaded
2. The .env variables override any variables set in other app files (solr.yml, fedora.yml, etc.)
Are these statement accurate or am I way off?

**Comment by orangewolf** [comment]
Shana March 2022
---
To be honest, I don't use stack car. I would need time to read its scripts before responding accurately. Rob wrote stack car though so he'd be a point of reference too if I can't be.

My basic understanding is that it's meant to be a wrapper to help add to + alias some docker commands. I think stack car expects presence of .env.development, .env and .env.production and may error if those files don't exist (don't quote me though I haven't looked or tried it yet!) I've never seen the error you captured above though ^

As far as overriding variables elsewhere, that shouldn't happen unless those files specifically reference them `ENV['SOLR_URL']`. There are usually fall backs in case those don't exist (see after || or : ). I'm not sure if I'm answering your q.

https://gitlab.com/notch8/louisville-hyku/-/blob/main/config/solr.yml#L3

**Comment by orangewolf** [comment]
Shana March 2022
---
stack car: https://gitlab.com/notch8/stack_car

**Comment by orangewolf** [comment]
Randy March 2022
---
@ShanaLMoore I will be able to do more docker testing tomorrow and get back to you. Also, it looks like https://gitlab.com/notch8/stack_car is throwing a 404.[@ShanaLMoore](https://github.com/ShanaLMoore) I will be able to do more docker testing tomorrow and get back to you. Also, it looks like https://gitlab.com/notch8/stack_car is throwing a 404.

**Comment by orangewolf** [comment]
Shana March 2022
---
gotcha, that makes sense. I wasn't sure you had permissions and should've checked. But I'm also not sure if it's OK to change permissions so will also need to check with that too.

I was hoping you'd be able to see the gem and read through what it does vs waiting around for me :smile:
