### ISSUE TITLE
Yarn Install Fails

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#126]
# Summary
Yarn Install Fails During Code Upgrade

yarn install yarn install v1.22.5 $ rm -rf ./public/uv \[1/4\] Resolving packages... success Already up-to-date. $ yarn run uv-install && yarn run uv-config yarn run v1.22.5 $ shx cp -r ./node_modules/universalviewer/dist ./public/uv internal/modules/cjs/loader.js:638 throw err; ^

Error: Cannot find module './config' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15) at Function.Module._load (internal/modules/cjs/loader.js:562:25) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at Object. (/home/deploy/hyku/node_modules/.bin/shx:10:15) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

# Acceptance Criteria

* [ ]

# Screenshots or Video
<details>
<summary></summary>

</details>

# Testing Instructions
Url:
*

# Notes
## Engineering Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by orangewolf** [comment]
Alisha February 2022
---
[#56 (closed)](https://github.com/notch8/louisville-hyku/-/issues/56), [#57 (closed)](https://github.com/notch8/louisville-hyku/-/issues/57), [#58 (closed)](https://github.com/notch8/louisville-hyku/-/issues/58) and [#59 (closed)](https://github.com/notch8/louisville-hyku/-/issues/59) are all believed to be issues related to [@rtkuehn](https://github.com/rtkuehn)'s local set up. [@summer-cook](https://github.com/summer-cook) [@ShanaLMoore](https://github.com/ShanaLMoore) nor myself are experiencing these errors in our dev environment at the moment.
randy and [@orangewolf](https://github.com/orangewolf) are already set to meet about [#13 (closed)](https://github.com/notch8/louisville-hyku/-/issues/13), and hoping the environment issues will be resolved at that time.

**Comment by orangewolf** [comment]
Shana March 2022
---
@rtkuehn Is this still any issue?[@rtkuehn](https://github.com/rtkuehn) Is this still any issue?

**Comment by orangewolf** [comment]
Randy March 2022
---
No, I believe this issue has been resolved. Thank you
