### ISSUE TITLE
bulkrax error

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#33]
I believe the slug changes are impacting the way bulkrax functions...

![Image](https://user-images.githubusercontent.com/1054448/203151435-85f447e0-6bf2-4b66-b6b7-093f74252988.png)

Starts here: https://github.com/samvera-labs/bulkrax/blob/bd683499bb52ae5df130f1fb266662ae55614767/app/jobs/bulkrax/create_relationships_job.rb#L40

Does identifier need to be a slug instead?

![Image](https://user-images.githubusercontent.com/1054448/203151493-330becf3-d15f-40c7-8d87-6844700c29f2.png)

## Acceptance Critera

- [ ] A user should be able to successfully import with bulkrax. 
- [ ] A user should be able to successfully re run bulkrax importers

**Comment by orangewolf** [comment]
Shana September 2022
---
## dev notes

this works: ActiveFedora::Base.find(t.identifier.first) => it falls into [super(*args)](https://gitlab.com/notch8/louisville-hyku/-/blob/main/app/models/custom_slugs/custom_slugs_decorator.rb#L30) and returns a result even though this isn't an "id"
t.identifier => ["ULUA 1909_The_Colonel_Page_001"]

However, for some reason it is not working when identifier = "ULUA Yearbooks" 
=> 
```
URI::InvalidURIError: bad URI(is not URI?): "http://fcrepo:8080/rest/ef32487f-4192-4504-8e05-30fe6e481dd6/UL/UA/ Y/ea/ULUA Yearbooks"
from /usr/local/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split'
Caused by URI::InvalidURIError: bad URI(is not URI?): "http://fcrepo:8080/rest/ef32487f-4192-4504-8e05-30fe6e481dd6/UL/UA/ Y/ea/ULUA Yearbooks"
from /usr/local/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split'
```

**Comment by orangewolf** [comment]
Shana September 2022
---
Closing, this error was caused by an invalid csv
