### ISSUE TITLE
LV server path import issues

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#64]
Per Rachel’s comment below….

When attempting an import to our Docker setup, each importer instantaneously adds the majority of the records in the import to the "Entries Failed" column (with an error message of RunTimeError - X file not found), then processes a very small number of the files (with no rhyme or reason as to their order in the CSV, or their size relative to one another) as if nothing is wrong with them. 

The exact same CSV and files can successfully complete an import with no failures/errors if uploaded as a Zip. The exact same CSV and files can also successfully complete an import to our pre-existing Dev server via the filepath.

**Comment by orangewolf** [comment]
Per Rachel’s comment below….

When attempting an import to our Docker setup, each importer instantaneously adds the majority of the records in the import to the "Entries Failed" column (with an error message of RunTimeError - X file not found), then processes a very small number of the files (with no rhyme or reason as to their order in the CSV, or their size relative to one another) as if nothing is wrong with them. 

The exact same CSV and files can successfully complete an import with no failures/errors if uploaded as a Zip. The exact same CSV and files can also successfully complete an import to our pre-existing Dev server via the filepath.

**Comment by orangewolf** [comment]
Related Merge Requests
---
[Move original volume to worker pod](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/53)

**Comment by orangewolf** [comment]
Alisha August 2022
---
[@rtkuehn](https://github.com/rtkuehn) can you update the description above with the problem you all are experiencing just so we can track it? I know LV's server team is looking at it, but just so we have the info if we need to circle back around to this

**Comment by orangewolf** [comment]
Alisha August 2022
---
example importer: https://lv-hyku-staging.notch8.cloud/importers/52/edit?locale=en

below is an image representing that path in our container on staging.
![Image](https://user-images.githubusercontent.com/1054448/203813980-5cdb0d84-2e43-4c3c-9794-c4538c3d8dea.png)

**Comment by orangewolf** [comment]
Shana August 2022
---
Thanks for making a ticket @alishaevn 

@rtkuehn could you also give us an idea of what your infrastructure looks like and what tools y’all use? We may need to pull in support from our dev ops team and having such details could help. 

As you know our apps are dockerized. We deploy and manage them via kubernetes clusters, with Rancher. 

As Alisha mentioned, we mount volumes for persisting directories, like our file systems’ import and upload directories. In Alisha’s example above we added one called originals and synced the provided sample data into it. 

If we sync files into the added directory without mounting a volume first, those files get wiped each time a deploy happens. 

Since it all lives on the same server we are able to reference the server’s file paths to the data we want to import, using bulkrax. And yes, having a slash in front of app is important! (and a gotcha). See Alisha's screenshot and example above - we'd want to use the entire output of pwd.

In our examples, we are still importing zipped files that live on our server though, if the csvs require files. If you select the csv alone, you can expect to get the file not found error in sidekiq, if that CSV is referencing files. 

If you need to select a csv separate from its files, you may want to set up browse everything: https://github.com/samvera/browse-everything

**Comment by orangewolf** [comment]
Randy August 2022
---
@ShanaLMoore Below is the information I received from Andy (Office of Library Technology): 

> Per Randy’s earlier e-mail, this is what I was trying to do via docker-compose and Docker on Ubuntu 20.  So, I’m basically attempting to mount the  \\libs-shared\groups\digital\HykuImports directly to the docker network as a volume called HykuImports as a samba share.  I then have been mounting this volume into the hyku_web_1 container using ‘HykuImports:/media/HykuImports’
> 
> This is what I was trying to do within the docker-compose.yml file, taken from the initial volumes section (with username/password blanked out):
>

![Image](https://user-images.githubusercontent.com/1054448/203814468-90b83dba-321e-44ee-94ef-af92f1d5f2d4.png)


> 
> Before, we were using /etc/fstab and mounting our HykuImports folder locally to the server and then adding it to the container as a volume like this:
> 
> ‘/media/HykuImports:/media/HykuImports’

**Comment by orangewolf** [comment]
Shana August 2022
---
@rtkuehn And I assume his above attempts did not work?

Also I found [this PR](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/53/diffs) related to us adding the originals volume. We added it our helm values and we deploy with helm. The docker-compose file is only for local dev. How do you all deploy?[@rtkuehn](https://github.com/rtkuehn) And I assume his above attempts did not work?
Also I found [this PR](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/53/diffs) related to us adding the originals volume. We added it our helm values and we deploy with helm. The docker-compose file is only for local dev. How do you all deploy?

**Comment by orangewolf** [comment]
Randy August 2022
---
@ShanaLMoore @rachel.howard Before we had a chance to tests any of the new options, We ran into a some server problems during and are currently in the process of correcting them. I expect that we'll test the options you shared when it's back online.[@ShanaLMoore](https://github.com/ShanaLMoore) [@rachel.howard](https://github.com/rachel.howard) Before we had a chance to tests any of the new options, We ran into a some server problems during and are currently in the process of correcting them. I expect that we'll test the options you shared when it's back online.

**Comment by orangewolf** [comment]
Rachel August 2022
---
When attempting an import to our Docker setup, each importer instantaneously adds the majority of the records in the import to the "Entries Failed" column (with an error message of RunTimeError - X file not found), then processes a very small number of the files (with no rhyme or reason as to their order in the CSV, or their size relative to one another) as if nothing is wrong with them. The exact same CSV and files can successfully complete an import with no failures/errors if uploaded as a Zip. The exact same CSV and files can also successfully complete an import to our pre-existing Dev server via the filepath.

**Comment by orangewolf** [comment]
Shana August 2022
---
TODO: @ShanaLMoore to share details with dev ops team

**Comment by orangewolf** [comment]
Shana August 2022
---
@rtkuehn Checking back in on the progress of this. Do we need to set up a pairing session? If so, could you send some available times? I'll probably need to loop Rob in for help.[@rtkuehn](https://github.com/rtkuehn) Checking back in on the progress of this. Do we need to set up a pairing session? If so, could you send some available times? I'll probably need to loop Rob in for help.

**Comment by orangewolf** [comment]
Randy August 2022
---
I wanted to clarify what we're experiencing before we set up a pairing session.

When we specify an attached volume as the import path, most of the files end up throwing a RuntimeError (File does not exist). 

First, Bulkrax will throw an error saying it can't find the CSV file. This usually occurs a couple times.

<details><summary>No such file or directory @ rb_sysopen - /media/docker_share/sim_test2/simmonola_test2.csv</summary>
[35;1mworker_1          |[0m E, [2022-08-19T11:05:37.310280 #1] ERROR -- : [ActiveJob] [Bulkrax::ImporterJob] [2f39baa1-7932-4f3b-b376-9b7de3324fea] Error performing Bulkrax::ImporterJob (Job ID: 2f39baa1-7932-4f3b-b376-9b7de3324fea) from Sidekiq(import) in 3.82ms: Errno::ENOENT (No such file or directory @ rb_sysopen - /media/docker_share/sim_test2/simmonola_test2.csv):
</details>

Once Bulkrax finds the CSV file, the import begins.

<details><summary>Bulkrax Column automatically matched file, Simmonola_1921_General_Student_Body.jpg</summary>
[35;1mworker_1          |[0m I, [2022-08-19T11:06:38.342759 #1]  INFO -- : [ActiveJob] [Bulkrax::ImportWorkJob] [cf5142e3-919e-4afe-ab5f-ff947503671f] Bulkrax Column automatically matched file, Simmonola_1921_General_Student_Body.jpg
</details>

Then it throws an error because it can't find the JPG.

<details><summary>"File /media/docker_share/sim_test2/files/Simmonola_1921_General_Student_Body.jpg does not exist"</summary>
[35;1mworker_1          |[0m D, [2022-08-19T11:06:38.461842 #1] DEBUG -- : [ActiveJob] [Bulkrax::ImportWorkJob] [cf5142e3-919e-4afe-ab5f-ff947503671f]   [1m[36mBulkrax::Status Create (8.7ms)[0m  [1m[32mINSERT INTO "bulkrax_statuses" ("status_message", "error_class", "error_message", "error_backtrace", "statusable_id", "statusable_type", "runnable_id", "runnable_type", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"[0m  [["status_message", "Failed"], ["error_class", "RuntimeError"], ["error_message", "File /media/docker_share/sim_test2/files/Simmonola_1921_General_Student_Body.jpg does not exist"], ["error_backtrace", "---\n- \"/usr/local/bundle/bundler/gems/bulkrax-d6faf2f9bd8c/app/models/bulkrax/csv_entry.rb:289:in\n  `path_to_file'\"\n- \"/usr/local/bundle/bundler/gems/bulkrax-d6faf2f9bd8c/app/models/bulkrax/csv_entry.rb:91:in\n  `block in add_file'\"\n- \"/usr/local/bundle/bundler/gems/bulkrax-d6faf2f9bd8c/app/models/bulkrax/csv_entry.rb:88:in\n  `map'\"\n- \"/usr/local/bundle/bundler/gems/bulkrax-d6faf2f9bd8c/app/models/bulkrax/csv_entry.rb:88:in\n  `add_file'\"\n- \"/usr/local/bundle/bundler/gems/bulkrax-d6faf2f9bd8c/app/models/bulkrax/csv_entry.rb:67:in\n  `add_metadata_for_model'\"\n- \"/usr/local/bundle/bundler/gems/bulkrax-d6faf2f9bd8c/app/models/bulkrax/csv_entry.rb:47:in\n  `build_metadata'\"\n- \"/usr/local/bundle/bundler/gems/bulkrax-d6faf2f9bd8c/app/models/concerns/bulkrax/import_behavior.rb:10:in\n  `build_for_importer'\"\n- \"/usr/local/bundle/bundler/gems/bulkrax-d6faf2f9bd8c/app/models/bulkrax/entry.rb:81:in\n  `build'\"\n- \"/usr/local/bundle/bundler/gems/bulkrax-d6faf2f9bd8c/app/jobs/bulkrax/import_work_job.rb:10:in\n  `perform'\"\n- \"/usr/local/bundle/gems/activejob-5.2.7.1/lib/active_job/execution.rb:39:in `block\n  in perform_now'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:109:in\n  `block in run_callbacks'\"\n- \"/usr/local/bundle/gems/sentry-raven-2.13.0/lib/raven/integrations/rails/active_job.rb:13:in\n  `block (2 levels) in included'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:118:in\n  `instance_exec'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:118:in\n  `block in run_callbacks'\"\n- \"/usr/local/bundle/gems/i18n-1.10.0/lib/i18n.rb:328:in `with_locale'\"\n- \"/usr/local/bundle/gems/activejob-5.2.7.1/lib/active_job/translation.rb:9:in `block\n  (2 levels) in <module:Translation>'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:118:in\n  `instance_exec'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:118:in\n  `block in run_callbacks'\"\n- \"/usr/local/bundle/gems/activejob-5.2.7.1/lib/active_job/logging.rb:26:in `block\n  (4 levels) in <module:Logging>'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:168:in\n  `block in instrument'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/notifications/instrumenter.rb:23:in\n  `instrument'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:168:in\n  `instrument'\"\n- \"/usr/local/bundle/gems/activejob-5.2.7.1/lib/active_job/logging.rb:25:in `block\n  (3 levels) in <module:Logging>'\"\n- \"/usr/local/bundle/gems/activejob-5.2.7.1/lib/active_job/logging.rb:46:in `block\n  in tag_logger'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/tagged_logging.rb:71:in\n  `block in tagged'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/tagged_logging.rb:28:in\n  `tagged'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/tagged_logging.rb:71:in\n  `tagged'\"\n- \"/usr/local/bundle/gems/activejob-5.2.7.1/lib/active_job/logging.rb:46:in `tag_logger'\"\n- \"/usr/local/bundle/gems/activejob-5.2.7.1/lib/active_job/logging.rb:22:in `block\n  (2 levels) in <module:Logging>'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:118:in\n  `instance_exec'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:118:in\n  `block in run_callbacks'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:136:in\n  `run_callbacks'\"\n- \"/usr/local/bundle/gems/activejob-5.2.7.1/lib/active_job/execution.rb:38:in `perform_now'\"\n- \"/app/samvera/hyrax-webapp/lib/active_job_tenant.rb:38:in `block in perform_now'\"\n- \"/app/samvera/hyrax-webapp/lib/active_job_tenant.rb:57:in `block in switch'\"\n- \"/usr/local/bundle/gems/apartment-2.2.1/lib/apartment/adapters/abstract_adapter.rb:85:in\n  `switch'\"\n- \"/usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `switch'\"\n- \"/app/samvera/hyrax-webapp/lib/active_job_tenant.rb:56:in `switch'\"\n- \"/app/samvera/hyrax-webapp/lib/active_job_tenant.rb:37:in `perform_now'\"\n- \"/usr/local/bundle/gems/activejob-5.2.7.1/lib/active_job/execution.rb:24:in `block\n  in execute'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:109:in\n  `block in run_callbacks'\"\n- \"/usr/local/bundle/gems/activejob-5.2.7.1/lib/active_job/railtie.rb:28:in `block\n  (4 levels) in <class:Railtie>'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/execution_wrapper.rb:90:in\n  `wrap'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/reloader.rb:73:in\n  `block in wrap'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/execution_wrapper.rb:86:in\n  `wrap'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/reloader.rb:72:in\n  `wrap'\"\n- \"/usr/local/bundle/gems/activejob-5.2.7.1/lib/active_job/railtie.rb:27:in `block\n  (3 levels) in <class:Railtie>'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:118:in\n  `instance_exec'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:118:in\n  `block in run_callbacks'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:136:in\n  `run_callbacks'\"\n- \"/usr/local/bundle/gems/activejob-5.2.7.1/lib/active_job/execution.rb:22:in `execute'\"\n- \"/usr/local/bundle/gems/activejob-5.2.7.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in\n  `perform'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:196:in `execute_job'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:164:in `block (2\n  levels) in process'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/middleware/chain.rb:138:in `block\n  in invoke'\"\n- \"/usr/local/bundle/gems/sentry-raven-2.13.0/lib/raven/integrations/sidekiq.rb:9:in\n  `call'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/middleware/chain.rb:140:in `block\n  in invoke'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:163:in `block in\n  process'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:136:in `block (6\n  levels) in dispatch'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/job_retry.rb:112:in `local'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:135:in `block (5\n  levels) in dispatch'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/rails.rb:14:in `block in call'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/execution_wrapper.rb:90:in\n  `wrap'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/reloader.rb:73:in\n  `block in wrap'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/execution_wrapper.rb:90:in\n  `wrap'\"\n- \"/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/reloader.rb:72:in\n  `wrap'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/rails.rb:13:in `call'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:131:in `block (4\n  levels) in dispatch'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:257:in `stats'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:126:in `block (3\n  levels) in dispatch'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/job_logger.rb:13:in `call'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:125:in `block (2\n  levels) in dispatch'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/job_retry.rb:79:in `global'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:124:in `block in\n  dispatch'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/logger.rb:11:in `with'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/job_logger.rb:33:in `prepare'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:123:in `dispatch'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:162:in `process'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:78:in `process_one'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:68:in `run'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/util.rb:43:in `watchdog'\"\n- \"/usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/util.rb:52:in `block in safe_thread'\"\n"], ["statusable_id", 1594], ["statusable_type", "Bulkrax::Entry"], ["runnable_id", 11], ["runnable_type", "Bulkrax::ImporterRun"], ["created_at", "2022-08-19 11:06:38.450226"], ["updated_at", "2022-08-19 11:06:38.450226"]]
</details>

This happens with parent/child JPGs, parent/child PDFs, and standard JPG imports. It doesn't matter if the volume is on the host or a different server. However, zip file imports from a mounted volume and files imported directly from within the container work fine. Well, mostly fine...they usually remain "pending" with records enqueued after Sidekiq finishes processing the import.

![Screen_Shot_2022-08-19_at_11.50.08_AM](/uploads/f83e742609739a81d60a55c64e2cb560/Screen_Shot_2022-08-19_at_11.50.08_AM.png)

We're running bulkrax (3.1.2)

Volumes are mounted in docker-compose.yml:

<details><summary>/home/deploy/docker_share:/media/docker_share</summary>
  web:

    volumes:
      - '/home/deploy/docker_share:/media/docker_share'
      - 'HykuImports:/media/HykuImports'
      - 'uploads:/app/samvera/hyrax-webapp/public/uploads'
      - 'assets:/app/samvera/hyrax-webapp/public/assets'
      - 'cache:/app/samvera/hyrax-webapp/tmp/cache'
      - '.:/app/samvera/hyrax-webapp'...
</details>

hyku_web_1 log: 
[hyku_web_1_sim2_test7_20220819.log](/uploads/f215fc94fde69c865855721085f9b2e8/hyku_web_1_sim2_test7_20220819.log)

hyku_worker_1 log: 
[hyku_worker_1_sim2_test7_20220819.log](/uploads/1d415587a69b3e442a82ad829a309a70/hyku_worker_1_sim2_test7_20220819.log)

/cc @rachel.howard

**Comment by orangewolf** [comment]
Shana August 2022
---
@rtkuehn Do you have access to the server? Can you take a screenshot of this dir? `ls -a /media/docker_share/sim_test2/`


Then take a screenshot of the output of `ls -a /media/docker_share/sim_test2/files/`

**Comment by orangewolf** [comment]
Randy August 2022
---
The simmonola_test2.csv import was tested multiple times. Each time different JPGs failed/succeeded to load.


![Image](https://user-images.githubusercontent.com/1054448/203815499-fb9efd83-4fe3-4873-a14c-5564ce10d249.png)

**Comment by orangewolf** [comment]
Shana August 2022
---
@rtkuehn I sent you an invite to pair with Rob, tomorrow at 10AM PST. Can you make it?[@rtkuehn](https://github.com/rtkuehn) I sent you an invite to pair with Rob, tomorrow at 10AM PST. Can you make it?

**Comment by orangewolf** [comment]
Randy August 2022
---
Sure...that works!

**Comment by orangewolf** [comment]
Shana August 2022
---
to close this loop,

the volume needed to be mounted on the worker container.
