### ISSUE TITLE
Bulkrax Load RSolr Error on Dev Server

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#99]
This may or may not help diagnose the connection error we're seeing on our dev server.

Bulkrax Log:

```
Errored at: 2022-03-24 13:37:57 UTC

Error: RSolr::Error::Http - RSolr::Error::Http - 404 Not Found Error: <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 404 Not Found</title> </head> <body><h2>HTTP ERROR 404 Not Found</h2> <table> <tr><th>URI:</th><td>/solr/select</td></tr> <tr><th>STATUS:</th><td>404</td></tr> <tr><th>MESSAGE:</th><td>Not Found</td></tr> <tr><th>SERVLET:</th><td>default</td></tr> URI: http://localhost:8983/solr/select?wt=json&fl=id&q=_query_%3A%22%7B%21raw+f%3Dhas_model_ssim%7DCollection%22+AND+_query_%3A%22%7B%21field+f%3Didentifier_tesim%7DEwing+Dairy+Collection%22&qt=standard&sort=system_create_dtsi+asc&start=0&rows=1000 Backtrace: /home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rsolr-2.4.0/lib/rsolr/client.rb:220:in `rescue in execute' /home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rsolr-2.4.0/lib/rsolr/client.rb:208:in `execute' /home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rsolr-2.4.0/lib/rsolr/client.rb:79:in `paginate' /home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:156:in `block in search_in_batches' /home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:154:in `loop' /home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:154:in `search_in_batches' /home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:119:in `find_each' /home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation.rb:152:in `each' /home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/factories/bulkrax/object_factory.rb:92:in `detect' /home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/factories/bulkrax/object_factory.rb:92:in `search_by_identifier' /home/deploy/hyku/app/factories/bulkrax/object_factory_decorator.rb:18:in `find'

Error Trace:

/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rsolr-2.4.0/lib/rsolr/client.rb:220:in `rescue in execute'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rsolr-2.4.0/lib/rsolr/client.rb:208:in `execute'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rsolr-2.4.0/lib/rsolr/client.rb:79:in `paginate'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:156:in `block in search_in_batches'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:154:in `loop'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:154:in `search_in_batches'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:119:in `find_each'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation.rb:152:in `each'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/factories/bulkrax/object_factory.rb:92:in `detect'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/factories/bulkrax/object_factory.rb:92:in `search_by_identifier'
/home/deploy/hyku/app/factories/bulkrax/object_factory_decorator.rb:18:in `find'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/factories/bulkrax/object_factory.rb:37:in `run'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/factories/bulkrax/object_factory.rb:49:in `run!'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/models/concerns/bulkrax/import_behavior.rb:13:in `build_for_importer'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/models/bulkrax/entry.rb:85:in `build'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/jobs/bulkrax/import_collection_job.rb:11:in `perform'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/execution.rb:39:in `block in perform_now'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sentry-raven-2.13.0/lib/raven/integrations/rails/active_job.rb:13:in `block (2 levels) in included'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/i18n-1.9.1/lib/i18n.rb:323:in `with_locale'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `block in instrument'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `instrument'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/logging.rb:46:in `block in tag_logger'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `tagged'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/logging.rb:46:in `tag_logger'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/execution.rb:38:in `perform_now'
/home/deploy/hyku/lib/active_job_tenant.rb:38:in `block in perform_now'
/home/deploy/hyku/lib/active_job_tenant.rb:57:in `block in switch'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/apartment-2.2.1/lib/apartment/adapters/abstract_adapter.rb:85:in `switch'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `switch'
/home/deploy/hyku/lib/active_job_tenant.rb:56:in `switch'
/home/deploy/hyku/lib/active_job_tenant.rb:37:in `perform_now'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/execution.rb:18:in `perform_now'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/parsers/bulkrax/csv_parser.rb:114:in `block in create_collections'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/parsers/bulkrax/csv_parser.rb:88:in `each'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/parsers/bulkrax/csv_parser.rb:88:in `each_with_index'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/parsers/bulkrax/csv_parser.rb:88:in `create_collections'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/models/bulkrax/importer.rb:137:in `import_collections'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/jobs/bulkrax/importer_job.rb:21:in `import'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/bulkrax-0adff8f0b541/app/jobs/bulkrax/importer_job.rb:12:in `perform'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/execution.rb:39:in `block in perform_now'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sentry-raven-2.13.0/lib/raven/integrations/rails/active_job.rb:13:in `block (2 levels) in included'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/i18n-1.9.1/lib/i18n.rb:328:in `with_locale'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `block in instrument'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `instrument'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/logging.rb:46:in `block in tag_logger'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `tagged'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/logging.rb:46:in `tag_logger'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/execution.rb:38:in `perform_now'
/home/deploy/hyku/lib/active_job_tenant.rb:38:in `block in perform_now'
/home/deploy/hyku/lib/active_job_tenant.rb:57:in `block in switch'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/apartment-2.2.1/lib/apartment/adapters/abstract_adapter.rb:85:in `switch'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `switch'
/home/deploy/hyku/lib/active_job_tenant.rb:56:in `switch'
/home/deploy/hyku/lib/active_job_tenant.rb:37:in `perform_now'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/execution.rb:24:in `block in execute'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/reloader.rb:73:in `block in wrap'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/execution_wrapper.rb:83:in `wrap'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/reloader.rb:72:in `wrap'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/execution.rb:22:in `execute'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-5.2.6/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:196:in `execute_job'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sentry-raven-2.13.0/lib/raven/integrations/sidekiq.rb:9:in `call'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:163:in `block in process'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/job_retry.rb:112:in `local'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/rails.rb:14:in `block in call'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/reloader.rb:73:in `block in wrap'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/reloader.rb:72:in `wrap'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/rails.rb:13:in `call'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:257:in `stats'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/job_logger.rb:13:in `call'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/job_retry.rb:79:in `global'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/logger.rb:11:in `with'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/job_logger.rb:33:in `prepare'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:123:in `dispatch'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:162:in `process'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:78:in `process_one'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:68:in `run'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/util.rb:43:in `watchdog'
/home/deploy/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
```

**Comment by orangewolf** [comment]
Randy April 2022
---
Fixed
